# Simple Linear Regression from **scratch**

## Defining our class

In [32]:
class SimpleLR_fromScratch:
    def __init__(self):
        self.m = None
        self.b = None

    def fit(self, x_train, y_train):
        num = 0
        den = 0

        for i in range(x_train.shape[0]):
            num = num + ((x_train[i]-x_train.mean()) * (y_train[i]-y_train.mean()))
            den += ((x_train[i]-x_train.mean()) * (x_train[i]-x_train.mean()))

            self.m = num/den
            self.b = y_train.mean() - (self.m*x_train.mean())

    def predict(self, x_test):
        return (self.m*x_test) + self.b

    def slope(self):
        return self.m

    def intercept(self):
        return self.b

## Checking our class

### Loading and splitting dataset

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('E:/Dataset/placement_package.csv')

In [4]:
df.head()

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57


In [14]:
x = df.iloc[:, 0].values
y = df.iloc[:, 1].values

In [7]:
from sklearn.model_selection import train_test_split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=3)

In [22]:
x_train

array([7.38, 8.35, 6.98, 7.25, 5.48, 7.04, 5.23, 6.68, 6.19, 7.94, 8.1 ,
       7.05, 6.42, 5.84, 7.77, 5.91, 5.38, 7.36, 8.15, 5.53, 8.99, 8.44,
       7.47, 6.59, 5.95, 6.05, 8.25, 6.93, 6.07, 6.85, 7.89, 5.84, 5.13,
       8.22, 6.5 , 8.65, 8.01, 6.53, 6.17, 7.9 , 6.09, 6.47, 5.42, 6.66,
       7.4 , 8.93, 7.66, 6.6 , 8.21, 6.14, 6.19, 6.26, 7.13, 8.09, 7.2 ,
       9.16, 7.91, 4.57, 6.1 , 7.87, 6.87, 7.6 , 9.58, 7.33, 7.69, 6.84,
       7.48, 7.76, 5.09, 7.56, 6.94, 6.76, 8.58, 5.32, 4.26, 6.61, 8.2 ,
       4.73, 6.29, 5.42, 5.64, 8.31, 7.14, 6.96, 7.15, 7.43, 6.31, 5.84,
       7.84, 7.89, 6.22, 7.56, 7.32, 5.99, 7.09, 8.37, 7.28, 8.63, 7.11,
       6.97, 6.12, 7.63, 6.61, 6.06, 7.08, 7.12, 4.79, 5.12, 6.94, 9.06,
       9.04, 6.94, 6.93, 6.86, 7.35, 5.94, 6.78, 8.11, 8.87, 5.83, 7.28,
       5.9 , 7.18, 5.1 , 6.35, 6.75, 6.34, 7.63, 6.22, 6.47, 5.98, 8.18,
       7.62, 7.3 , 7.11, 7.29, 5.61, 7.82, 5.11, 6.3 , 6.1 , 8.31, 6.93,
       8.13, 6.79, 6.93, 7.57, 8.6 , 7.39, 8.28, 7.

### Testing our model

In [33]:
lr = SimpleLR_fromScratch()

In [34]:
lr.fit(x_train, y_train)

In [28]:
x_test

array([9.38, 9.26, 7.19, 7.21, 6.22, 5.58, 7.28, 6.07, 5.79, 7.95, 7.14,
       8.44, 7.28, 6.19, 8.71, 6.75, 6.63, 7.42, 6.89, 6.92, 7.73, 4.85,
       8.94, 6.73, 5.88, 7.3 , 7.93, 5.12, 6.71, 7.61, 7.36, 5.84, 5.95,
       7.34, 8.62, 5.89, 6.94, 7.78, 6.51, 5.84])

In [29]:
y_test

array([4.02, 3.79, 2.4 , 3.24, 2.87, 2.17, 2.72, 2.26, 2.35, 4.14, 3.03,
       3.49, 3.65, 2.69, 4.08, 2.56, 2.79, 3.67, 2.7 , 3.09, 3.42, 1.54,
       3.65, 2.6 , 2.08, 3.33, 3.34, 2.01, 3.52, 2.77, 2.92, 3.26, 3.04,
       3.42, 4.36, 2.57, 3.57, 3.62, 2.89, 2.18])

In [35]:
lr.predict(x_test[0])

np.float64(4.3975123856466505)

In [39]:
lr.predict(x_test[1])

np.float64(4.326803453444561)

In [40]:
print(f'Slope: {lr.slope()}')
print(f'Intercept: {lr.intercept()}')

Slope: 0.5892411016840696
Intercept: -1.1295691481499235
